// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRqRth6C9PWWGvDpDRLCN9_q89jlGkpC4',
    appId: '1:765476694363:web:94a2d17978d81c3fa9d27e',
    messagingSenderId: '765476694363',
    projectId: 'nuelroncampustour',
    authDomain: 'nuelroncampustour.firebaseapp.com',
    storageBucket: 'nuelroncampustour.appspot.com',
    measurementId: 'G-YKBZP3W4V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr2n4MFoZlU1Kl8AK4fHNF6sXLwFXYWGk',
    appId: '1:765476694363:android:4824a1872a1f4058a9d27e',
    messagingSenderId: '765476694363',
    projectId: 'nuelroncampustour',
    storageBucket: 'nuelroncampustour.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApXt26AQtbAFK3TRALQzN9CeBm6Cr-WWE',
    appId: '1:765476694363:ios:2f8732500d2df664a9d27e',
    messagingSenderId: '765476694363',
    projectId: 'nuelroncampustour',
    storageBucket: 'nuelroncampustour.appspot.com',
    iosBundleId: 'com.example.nuelroncampustour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApXt26AQtbAFK3TRALQzN9CeBm6Cr-WWE',
    appId: '1:765476694363:ios:d35963dff74e5401a9d27e',
    messagingSenderId: '765476694363',
    projectId: 'nuelroncampustour',
    storageBucket: 'nuelroncampustour.appspot.com',
    iosBundleId: 'com.example.nuelroncampustour.RunnerTests',
  );
}
